
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION_ABRE = 32;
  public static final int NUMERO = 9;
  public static final int DE_LO_CONTRARIO = 29;
  public static final int LIT_BOOLEAN = 23;
  public static final int LIT_CARACTER = 21;
  public static final int IMPRIMIR = 35;
  public static final int FIN_METODO = 48;
  public static final int SI = 25;
  public static final int FUNCION = 49;
  public static final int MAYOR_O_IGUAL = 14;
  public static final int RESTA = 57;
  public static final int METODO = 46;
  public static final int ENTONCES = 28;
  public static final int FIN = 3;
  public static final int LIT_CADENA = 22;
  public static final int HASTA = 38;
  public static final int FIN_SI = 26;
  public static final int NOT = 20;
  public static final int AND = 19;
  public static final int ES_DIFERENTE = 17;
  public static final int CARACTER = 10;
  public static final int OR = 18;
  public static final int CORCHETE_CIERRA = 63;
  public static final int MIENTRAS = 41;
  public static final int COMO = 6;
  public static final int SUMA = 55;
  public static final int PUNTO_COMA = 52;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int MENOR_O_IGUAL = 15;
  public static final int error = 1;
  public static final int COMA = 64;
  public static final int FIN_FUNCION = 50;
  public static final int CADENA = 11;
  public static final int MODULO = 61;
  public static final int FIN_SEGUN = 34;
  public static final int MENOR = 13;
  public static final int O_SI = 27;
  public static final int FIN_MIENTRAS = 42;
  public static final int ASIGNACION = 24;
  public static final int MAYOR = 12;
  public static final int CON_VALOR = 7;
  public static final int POTENCIA = 60;
  public static final int CORCHETE_ABRE = 62;
  public static final int HASTA_QUE = 44;
  public static final int PARENTECIS_ABRE = 53;
  public static final int LIT_NUMERO = 56;
  public static final int IMPRIMIR_NL = 36;
  public static final int VARIABLE = 5;
  public static final int INGRESAR = 4;
  public static final int PARENTECIS_CIERRA = 54;
  public static final int CON_INCREMENTAL = 39;
  public static final int FIN_PARA = 40;
  public static final int REPETIR = 43;
  public static final int INTERROGACION_CIERRA = 33;
  public static final int SEGUN = 30;
  public static final int CON_PARAMETROS = 47;
  public static final int HACER = 31;
  public static final int PARA = 37;
  public static final int RETORNAR = 45;
  public static final int INICIO = 2;
  public static final int DIVISION = 58;
  public static final int EJECUTAR = 51;
  public static final int ES_IGUAL = 16;
  public static final int MULTIPLICACION = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "INGRESAR",
  "VARIABLE",
  "COMO",
  "CON_VALOR",
  "BOOLEAN",
  "NUMERO",
  "CARACTER",
  "CADENA",
  "MAYOR",
  "MENOR",
  "MAYOR_O_IGUAL",
  "MENOR_O_IGUAL",
  "ES_IGUAL",
  "ES_DIFERENTE",
  "OR",
  "AND",
  "NOT",
  "LIT_CARACTER",
  "LIT_CADENA",
  "LIT_BOOLEAN",
  "ASIGNACION",
  "SI",
  "FIN_SI",
  "O_SI",
  "ENTONCES",
  "DE_LO_CONTRARIO",
  "SEGUN",
  "HACER",
  "INTERROGACION_ABRE",
  "INTERROGACION_CIERRA",
  "FIN_SEGUN",
  "IMPRIMIR",
  "IMPRIMIR_NL",
  "PARA",
  "HASTA",
  "CON_INCREMENTAL",
  "FIN_PARA",
  "MIENTRAS",
  "FIN_MIENTRAS",
  "REPETIR",
  "HASTA_QUE",
  "RETORNAR",
  "METODO",
  "CON_PARAMETROS",
  "FIN_METODO",
  "FUNCION",
  "FIN_FUNCION",
  "EJECUTAR",
  "PUNTO_COMA",
  "PARENTECIS_ABRE",
  "PARENTECIS_CIERRA",
  "SUMA",
  "LIT_NUMERO",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "POTENCIA",
  "MODULO",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMA"
  };
}

