/* The following code was generated by JFlex 1.7.0 */

/* Analizador lexico */
package analizadores;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>AnalizadorLexico.jflex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\45\1\1\1\2\22\0\1\1\1\0\1\31"+
    "\1\0\1\14\2\0\1\13\2\0\1\5\3\0\1\12\1\4\1\6"+
    "\1\11\1\11\2\11\1\11\1\11\2\11\1\11\1\0\1\44\5\0"+
    "\1\17\1\41\1\22\1\43\1\37\1\34\1\35\1\7\1\24\2\7"+
    "\1\30\1\25\1\32\1\33\2\7\1\36\1\21\1\42\1\27\1\40"+
    "\2\7\1\26\1\7\4\0\1\10\1\0\1\17\1\41\1\22\1\43"+
    "\1\37\1\34\1\35\1\7\1\24\2\7\1\30\1\25\1\32\1\33"+
    "\2\7\1\36\1\21\1\42\1\27\1\40\2\7\1\26\1\7\1\15"+
    "\1\0\1\16\7\0\1\45\252\0\2\23\115\0\1\20\u1ea8\0\1\45"+
    "\1\45\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\11\1\1\4\1\5"+
    "\14\0\1\6\4\0\2\5\2\0\1\3\1\7\1\10"+
    "\12\0\1\11\7\0\1\12\17\0\1\13\1\14\6\0"+
    "\1\15\1\0\1\16\3\0\1\17\13\0\1\20\1\0"+
    "\1\21\1\0\1\22\2\0\1\23\2\0\1\24\16\0"+
    "\1\25\1\0\1\26\1\27\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\46\0\114\0\162\0\230\0\276\0\344"+
    "\0\u010a\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214"+
    "\0\u023a\0\46\0\u0260\0\u0286\0\230\0\u02ac\0\u02d2\0\u02f8"+
    "\0\u031e\0\u0344\0\u036a\0\u0390\0\u03b6\0\u03dc\0\u01a2\0\u01a2"+
    "\0\u0402\0\u0428\0\u044e\0\u0474\0\u049a\0\46\0\u04c0\0\u04e6"+
    "\0\u02ac\0\46\0\46\0\u050c\0\u0532\0\u0558\0\u057e\0\u05a4"+
    "\0\u05ca\0\u05f0\0\u0616\0\u063c\0\u0662\0\46\0\u0688\0\u06ae"+
    "\0\u06d4\0\u06fa\0\u0720\0\u0746\0\u076c\0\46\0\u0792\0\u07b8"+
    "\0\u07de\0\u0804\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8"+
    "\0\u090e\0\u0934\0\u095a\0\u0980\0\u09a6\0\u09cc\0\u09f2\0\u0a18"+
    "\0\u0a3e\0\u0a64\0\u0a8a\0\u0ab0\0\u0ad6\0\46\0\u0afc\0\46"+
    "\0\u0b22\0\u0b48\0\u0b6e\0\46\0\u0b94\0\u0bba\0\u0be0\0\u0c06"+
    "\0\u0c2c\0\u0c52\0\u0c78\0\u0c9e\0\u0cc4\0\u0cea\0\u0d10\0\46"+
    "\0\u0d36\0\46\0\u0d5c\0\46\0\u0d82\0\u0da8\0\46\0\u0dce"+
    "\0\u0df4\0\46\0\u0e1a\0\u0e40\0\u0e66\0\u0e8c\0\u0eb2\0\u0ed8"+
    "\0\u0efe\0\u0f24\0\u0f4a\0\u0f70\0\u0f96\0\u0fbc\0\u0fe2\0\u1008"+
    "\0\46\0\u102e\0\46\0\46\0\u1054\0\u107a\0\u10a0\0\u10c6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\2\1\6\1\2"+
    "\1\7\1\10\1\2\1\11\6\2\1\12\2\13\1\14"+
    "\3\2\1\15\1\16\1\2\1\17\2\2\1\20\1\2"+
    "\1\21\2\2\1\22\52\0\1\3\46\0\1\23\1\24"+
    "\46\0\1\25\2\0\1\25\1\26\42\0\1\27\7\0"+
    "\1\27\1\0\2\27\1\0\5\27\1\0\12\27\10\0"+
    "\1\10\2\0\1\10\1\26\33\0\14\30\1\31\31\30"+
    "\17\0\1\32\13\0\1\33\44\0\1\34\32\0\1\35"+
    "\17\0\1\36\6\0\31\37\1\40\14\37\27\0\1\41"+
    "\41\0\2\42\41\0\2\43\57\0\1\44\12\0\2\23"+
    "\1\45\1\46\42\23\5\47\1\50\40\47\6\0\1\51"+
    "\2\0\1\51\42\0\2\27\1\52\1\27\5\0\1\27"+
    "\1\0\2\27\1\0\5\27\1\0\12\27\15\0\1\53"+
    "\45\0\1\53\1\0\1\54\66\0\1\55\4\0\1\56"+
    "\27\0\1\57\4\0\1\60\36\0\2\61\10\0\1\62"+
    "\36\0\1\63\51\0\1\64\40\0\1\65\52\0\1\66"+
    "\23\0\1\67\70\0\1\70\15\0\1\46\42\0\5\47"+
    "\1\71\40\47\4\0\1\46\1\50\46\0\1\72\2\0"+
    "\1\72\5\0\1\73\45\0\1\74\65\0\1\75\41\0"+
    "\1\76\22\0\1\77\57\0\1\100\61\0\1\101\42\0"+
    "\1\102\45\0\1\103\51\0\1\104\31\0\2\105\16\0"+
    "\1\106\32\0\1\107\15\0\4\47\1\46\1\71\40\47"+
    "\16\0\1\30\47\0\2\110\46\0\1\111\55\0\1\112"+
    "\53\0\1\113\30\0\2\114\60\0\1\115\44\0\1\116"+
    "\45\0\1\117\45\0\1\120\44\0\1\121\33\0\2\122"+
    "\60\0\1\123\30\0\1\124\65\0\1\125\22\0\1\126"+
    "\45\0\1\127\61\0\1\130\32\0\2\131\34\0\1\132"+
    "\45\0\1\133\70\0\1\134\41\0\1\135\52\0\1\136"+
    "\30\0\1\137\50\0\1\140\62\0\1\141\36\0\1\142"+
    "\34\0\1\143\61\0\1\144\45\0\1\145\31\0\1\146"+
    "\65\0\1\147\40\0\1\150\36\0\2\151\57\0\1\152"+
    "\42\0\1\153\50\0\1\154\17\0\1\155\45\0\1\156"+
    "\65\0\1\157\53\0\1\160\34\0\1\161\56\0\1\162"+
    "\32\0\2\163\44\0\2\164\60\0\1\165\25\0\1\166"+
    "\63\0\1\167\45\0\1\170\42\0\1\171\41\0\1\172"+
    "\46\0\1\173\45\0\1\174\60\0\1\175\32\0\1\176"+
    "\35\0\1\177\45\0\1\200\65\0\1\201\26\0\2\202"+
    "\54\0\1\203\45\0\1\204\37\0\1\205\52\0\1\206"+
    "\46\0\1\207\34\0\1\210\46\0\2\72\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4332];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\16\1\1\11\1\1\14\0\1\1\4\0"+
    "\1\1\1\11\2\0\1\1\2\11\12\0\1\11\7\0"+
    "\1\11\17\0\2\1\6\0\1\11\1\0\1\11\3\0"+
    "\1\11\13\0\1\11\1\0\1\11\1\0\1\11\2\0"+
    "\1\11\2\0\1\11\16\0\1\11\1\0\2\11\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico : " +yytext() + " Linea: " + (yyline + 1) + 
        " Columna: " + (yycolumn + 1));
            } 
            // fall through
          case 24: break;
          case 2: 
            { /* ignore */
            } 
            // fall through
          case 25: break;
          case 3: 
            { System.out.println("Se reconocio literalNumero"); return new Symbol(sym.LIT_NUMERO);
            } 
            // fall through
          case 26: break;
          case 4: 
            { System.out.println("Se reconocio punto y coma"); return new Symbol(sym.PUNTO_COMA);
            } 
            // fall through
          case 27: break;
          case 5: 
            { System.out.println("Se reconocio el comentario");/*ignore*/
            } 
            // fall through
          case 28: break;
          case 6: 
            { System.out.println("Se reconocio el LITERAL CADENA"); return new Symbol(sym.LIT_CADENA);
            } 
            // fall through
          case 29: break;
          case 7: 
            { System.out.println("Se reconocio variable"); return new Symbol(sym.VARIABLE);
            } 
            // fall through
          case 30: break;
          case 8: 
            { System.out.println("Se reconocio el LITERAL caracter"); return new Symbol(sym.LIT_CARACTER);
            } 
            // fall through
          case 31: break;
          case 9: 
            { System.out.println("Se reconocio fin"); return new Symbol(sym.FIN);
            } 
            // fall through
          case 32: break;
          case 10: 
            { System.out.println("Se reconocio como"); return new Symbol(sym.COMO);
            } 
            // fall through
          case 33: break;
          case 11: 
            { return new Symbol(sym.MAYOR);
            } 
            // fall through
          case 34: break;
          case 12: 
            { return new Symbol(sym.MENOR);
            } 
            // fall through
          case 35: break;
          case 13: 
            { return new Symbol(sym.CADENA);
            } 
            // fall through
          case 36: break;
          case 14: 
            { System.out.println("Se reconocio inicio"); return new Symbol(sym.INICIO);
            } 
            // fall through
          case 37: break;
          case 15: 
            { System.out.println("Se reconocio numero"); return new Symbol(sym.NUMERO);
            } 
            // fall through
          case 38: break;
          case 16: 
            { return new Symbol(sym.BOOLEAN);
            } 
            // fall through
          case 39: break;
          case 17: 
            { return new Symbol(sym.CARACTER);
            } 
            // fall through
          case 40: break;
          case 18: 
            { System.out.println("Se reconocio ingresar"); return new Symbol(sym.INGRESAR);
            } 
            // fall through
          case 41: break;
          case 19: 
            { return new Symbol(sym.ES_IGUAL);
            } 
            // fall through
          case 42: break;
          case 20: 
            { System.out.println("Se reconocio con_valor"); return new Symbol(sym.CON_VALOR);
            } 
            // fall through
          case 43: break;
          case 21: 
            { return new Symbol(sym.ES_DIFERENTE);
            } 
            // fall through
          case 44: break;
          case 22: 
            { return new Symbol(sym.MAYOR_O_IGUAL);
            } 
            // fall through
          case 45: break;
          case 23: 
            { return new Symbol(sym.MENOR_O_IGUAL);
            } 
            // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
