/* The following code was generated by JFlex 1.7.0 */

/* Analizador lexico */
package analizadores;
import java_cup.runtime.*;

/* Seccion de declaraciones*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>AnalizadorLexico.jflex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\56\1\1\1\2\22\0\1\1\1\0\1\25"+
    "\1\0\1\22\2\0\1\21\2\0\1\5\2\0\1\40\1\12\1\4"+
    "\1\6\1\17\1\20\2\11\1\14\1\13\2\15\1\16\1\0\1\53"+
    "\2\0\1\41\2\0\1\32\1\50\1\45\1\31\1\27\1\34\1\46"+
    "\1\7\1\43\2\7\1\35\1\47\1\44\1\33\1\55\1\7\1\30"+
    "\1\37\1\52\1\51\1\26\2\7\1\54\1\7\4\0\1\10\1\0"+
    "\1\32\1\50\1\45\1\31\1\27\1\34\1\46\1\7\1\43\2\7"+
    "\1\35\1\47\1\44\1\33\1\55\1\7\1\30\1\37\1\52\1\51"+
    "\1\26\2\7\1\54\1\7\1\23\1\0\1\24\7\0\1\56\252\0"+
    "\2\42\115\0\1\36\u1ea8\0\1\56\1\56\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\16\1\1\4\1\5"+
    "\7\0\1\6\10\0\1\7\1\10\10\0\2\5\2\0"+
    "\1\3\1\11\1\12\7\0\1\13\26\0\1\14\12\0"+
    "\1\15\12\0\1\16\1\0\1\17\7\0\1\20\1\21"+
    "\6\0\1\22\1\23\2\0\1\24\1\0\1\25\17\0"+
    "\1\26\1\0\1\27\1\30\1\0\1\31\1\32\1\33"+
    "\6\0\1\34\11\0\1\35\2\0\1\36\4\0\1\37"+
    "\1\40\1\0\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\57\0\u03db"+
    "\0\u040a\0\274\0\u0439\0\u0468\0\u0497\0\u04c6\0\u0178\0\57"+
    "\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e"+
    "\0\57\0\57\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\57\0\u0814\0\u0843\0\u0439\0\57"+
    "\0\57\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04"+
    "\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c"+
    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\57"+
    "\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d"+
    "\0\u0f6c\0\u0f9b\0\57\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086"+
    "\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u1171\0\57\0\u11a0\0\57"+
    "\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\57"+
    "\0\57\0\u1490\0\u14bf\0\57\0\u14ee\0\57\0\u151d\0\u154c"+
    "\0\u157b\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4"+
    "\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\57\0\u17de\0\57"+
    "\0\57\0\u180d\0\57\0\u183c\0\57\0\u186b\0\u189a\0\u18c9"+
    "\0\u18f8\0\u1927\0\u1956\0\57\0\u1985\0\u19b4\0\u19e3\0\u1a12"+
    "\0\u1a41\0\u1a70\0\u1a9f\0\u1ace\0\u1afd\0\57\0\u1b2c\0\u1b5b"+
    "\0\57\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17\0\57\0\57\0\u1c46"+
    "\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\2\1\6\1\2"+
    "\1\7\1\10\1\2\6\10\1\11\3\2\1\12\1\13"+
    "\1\14\1\2\1\15\1\2\1\16\1\17\1\2\2\20"+
    "\1\21\1\2\2\22\1\23\1\24\1\2\1\25\1\26"+
    "\2\2\1\27\2\2\63\0\1\3\57\0\1\30\1\31"+
    "\57\0\1\32\2\0\1\32\1\33\6\32\45\0\1\34"+
    "\16\0\10\34\1\0\1\34\3\0\10\34\1\0\2\34"+
    "\7\0\1\10\2\0\1\10\1\33\6\10\36\0\22\35"+
    "\1\36\34\35\25\37\1\40\31\37\27\0\1\41\65\0"+
    "\2\42\4\0\1\43\41\0\1\44\37\0\1\45\100\0"+
    "\1\46\7\0\2\47\42\0\1\50\12\0\2\51\54\0"+
    "\1\52\61\0\1\53\2\0\1\54\60\0\1\55\37\0"+
    "\1\56\1\57\52\0\1\60\2\0\1\61\57\0\1\62"+
    "\23\0\2\30\1\63\1\64\53\30\5\65\1\66\51\65"+
    "\6\0\1\67\2\0\1\67\1\0\6\67\44\0\2\34"+
    "\1\70\1\34\1\0\6\34\5\0\10\34\1\0\1\34"+
    "\3\0\10\34\1\0\2\34\22\0\1\71\56\0\1\71"+
    "\1\0\1\72\63\0\1\73\36\0\1\74\120\0\1\75"+
    "\14\0\1\76\104\0\2\77\54\0\1\100\65\0\1\101"+
    "\60\0\1\102\52\0\2\103\2\0\1\104\65\0\1\105"+
    "\50\0\1\106\37\0\1\107\1\110\71\0\1\111\2\0"+
    "\1\112\53\0\1\113\66\0\1\114\35\0\1\115\26\0"+
    "\1\64\53\0\5\65\1\116\51\65\4\0\1\64\1\66"+
    "\64\0\1\117\1\0\1\120\1\121\1\122\70\0\1\123"+
    "\56\0\1\124\10\0\2\125\46\0\1\126\60\0\1\127"+
    "\63\0\2\130\51\0\2\131\27\0\1\132\117\0\1\133"+
    "\52\0\1\134\41\0\1\135\56\0\1\136\55\0\1\137"+
    "\61\0\1\140\53\0\1\141\37\0\1\142\101\0\1\143"+
    "\56\0\1\144\56\0\1\145\60\0\1\146\21\0\4\65"+
    "\1\64\1\116\51\65\13\0\4\147\46\0\1\147\2\0"+
    "\1\147\1\0\6\147\44\0\1\147\6\0\2\147\46\0"+
    "\1\120\10\0\1\120\1\150\70\0\1\151\66\0\2\152"+
    "\61\0\1\153\54\0\1\154\45\0\1\155\56\0\1\156"+
    "\61\0\2\157\63\0\1\160\54\0\2\161\42\0\1\162"+
    "\71\0\2\163\43\0\1\164\73\0\1\165\55\0\1\166"+
    "\40\0\1\167\60\0\1\170\56\0\1\171\55\0\1\172"+
    "\53\0\1\35\40\0\1\147\10\0\2\147\67\0\1\173"+
    "\61\0\1\174\73\0\1\175\52\0\1\176\21\0\1\177"+
    "\110\0\2\200\46\0\1\201\61\0\2\202\66\0\1\203"+
    "\42\0\1\204\75\0\1\205\36\0\1\206\56\0\1\207"+
    "\34\0\1\210\56\0\1\211\100\0\1\212\53\0\1\213"+
    "\56\0\1\214\61\0\1\215\53\0\1\216\74\0\1\217"+
    "\43\0\1\220\66\0\2\221\42\0\1\222\64\0\1\223"+
    "\54\0\1\224\56\0\1\225\67\0\1\226\42\0\1\131"+
    "\56\0\1\227\63\0\1\230\57\0\2\231\52\0\1\232"+
    "\53\0\1\233\56\0\1\234\56\0\1\235\61\0\1\236"+
    "\33\0\1\237\56\0\1\240\75\0\1\241\73\0\1\242"+
    "\22\0\1\243\76\0\1\244\70\0\2\245\55\0\2\246"+
    "\57\0\1\247\64\0\1\250\50\0\1\251\60\0\1\252"+
    "\56\0\1\253\62\0\1\254\34\0\1\255\63\0\1\256"+
    "\72\0\1\257\56\0\1\260\34\0\1\261\61\0\1\262"+
    "\56\0\1\263\56\0\1\264\54\0\1\265\63\0\1\266"+
    "\56\0\1\267\63\0\2\270\46\0\1\271\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7285];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\23\1\1\11\1\1\7\0\1\11\10\0"+
    "\2\11\10\0\1\1\1\11\2\0\1\1\2\11\7\0"+
    "\1\1\26\0\1\11\12\0\1\11\12\0\1\11\1\0"+
    "\1\11\7\0\2\1\6\0\2\11\2\0\1\11\1\0"+
    "\1\11\17\0\1\11\1\0\2\11\1\0\1\11\1\1"+
    "\1\11\6\0\1\11\11\0\1\11\2\0\1\11\4\0"+
    "\2\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 226) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico : " +yytext() + " Linea: " + (yyline + 1) + 
        " Columna: " + (yycolumn + 1));
            } 
            // fall through
          case 34: break;
          case 2: 
            { /* ignore */
            } 
            // fall through
          case 35: break;
          case 3: 
            { System.out.println("Se reconocio literalNumero"); return new Symbol(sym.LIT_NUMERO);
            } 
            // fall through
          case 36: break;
          case 4: 
            { System.out.println("Se reconocio punto y coma"); return new Symbol(sym.PUNTO_COMA);
            } 
            // fall through
          case 37: break;
          case 5: 
            { System.out.println("Se reconocio el comentario");/*ignore*/
            } 
            // fall through
          case 38: break;
          case 6: 
            { System.out.println("Se reconocio el LITERAL CADENA: " + yytext()); return new Symbol(sym.LIT_CADENA);
            } 
            // fall through
          case 39: break;
          case 7: 
            { System.out.println("Se reconocio el Si"); return new Symbol(sym.SI);
            } 
            // fall through
          case 40: break;
          case 8: 
            { System.out.println("Se reconocio con_valor"); return new Symbol(sym.ASIGNACION);
            } 
            // fall through
          case 41: break;
          case 9: 
            { System.out.println("Se reconocio variable"); return new Symbol(sym.VARIABLE);
            } 
            // fall through
          case 42: break;
          case 10: 
            { System.out.println("Se reconocio el LITERAL caracter"); return new Symbol(sym.LIT_CARACTER);
            } 
            // fall through
          case 43: break;
          case 11: 
            { System.out.println("Se reconocio fin"); return new Symbol(sym.FIN);
            } 
            // fall through
          case 44: break;
          case 12: 
            { return new Symbol(sym.O_SI);
            } 
            // fall through
          case 45: break;
          case 13: 
            { System.out.println("Se reconocio como"); return new Symbol(sym.COMO);
            } 
            // fall through
          case 46: break;
          case 14: 
            { System.out.println("Se reconocio el LITERAL booleana"); return new Symbol(sym.LIT_BOOLEAN);
            } 
            // fall through
          case 47: break;
          case 15: 
            { System.out.println("Se reconocio Segun"); return new Symbol(sym.SEGUN);
            } 
            // fall through
          case 48: break;
          case 16: 
            { return new Symbol(sym.MENOR);
            } 
            // fall through
          case 49: break;
          case 17: 
            { return new Symbol(sym.MAYOR);
            } 
            // fall through
          case 50: break;
          case 18: 
            { System.out.println("Se reconocio el FinSi"); return new Symbol(sym.FIN_SI);
            } 
            // fall through
          case 51: break;
          case 19: 
            { System.out.println("Se reconocio inicio"); return new Symbol(sym.INICIO);
            } 
            // fall through
          case 52: break;
          case 20: 
            { System.out.println("Se reconocio numero"); return new Symbol(sym.NUMERO);
            } 
            // fall through
          case 53: break;
          case 21: 
            { return new Symbol(sym.CADENA);
            } 
            // fall through
          case 54: break;
          case 22: 
            { return new Symbol(sym.BOOLEAN);
            } 
            // fall through
          case 55: break;
          case 23: 
            { System.out.println("Se reconocio es igual"); return new Symbol(sym.ES_IGUAL);
            } 
            // fall through
          case 56: break;
          case 24: 
            { return new Symbol(sym.ENTONCES);
            } 
            // fall through
          case 57: break;
          case 25: 
            { System.out.println("Se reconocio ingresar"); return new Symbol(sym.INGRESAR);
            } 
            // fall through
          case 58: break;
          case 26: 
            { System.out.println("Se reconocio\"imprimir\""); return new Symbol(sym.IMPRIMIR);
            } 
            // fall through
          case 59: break;
          case 27: 
            { return new Symbol(sym.CARACTER);
            } 
            // fall through
          case 60: break;
          case 28: 
            { System.out.println("Se reconocio con_valor"); return new Symbol(sym.CON_VALOR);
            } 
            // fall through
          case 61: break;
          case 29: 
            { System.out.println("Se reconocio\"imprimir_nl\""); return new Symbol(sym.IMPRIMIR_NL);
            } 
            // fall through
          case 62: break;
          case 30: 
            { return new Symbol(sym.ES_DIFERENTE);
            } 
            // fall through
          case 63: break;
          case 31: 
            { System.out.println("Se reconocio Menor o igual "); return new Symbol(sym.MENOR_O_IGUAL);
            } 
            // fall through
          case 64: break;
          case 32: 
            { return new Symbol(sym.MAYOR_O_IGUAL);
            } 
            // fall through
          case 65: break;
          case 33: 
            { return new Symbol(sym.DE_LO_CONTRARIO);
            } 
            // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
