
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION_ABRE = 31;
  public static final int NUMERO = 9;
  public static final int DE_LO_CONTRARIO = 28;
  public static final int LIT_BOOLEAN = 22;
  public static final int LIT_CARACTER = 20;
  public static final int IMPRIMIR = 34;
  public static final int SI = 24;
  public static final int MAYOR_O_IGUAL = 15;
  public static final int ENTONCES = 27;
  public static final int FIN = 3;
  public static final int LIT_CADENA = 21;
  public static final int FIN_SI = 25;
  public static final int ES_DIFERENTE = 18;
  public static final int CARACTER = 10;
  public static final int COMO = 6;
  public static final int PUNTO_COMA = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int MENOR_O_IGUAL = 16;
  public static final int error = 1;
  public static final int CADENA = 11;
  public static final int FIN_SEGUN = 33;
  public static final int MENOR = 14;
  public static final int O_SI = 26;
  public static final int ASIGNACION = 23;
  public static final int MAYOR = 13;
  public static final int CON_VALOR = 7;
  public static final int IMPRIMIR_NL = 35;
  public static final int LIT_NUMERO = 12;
  public static final int VARIABLE = 5;
  public static final int INGRESAR = 4;
  public static final int INTERROGACION_CIERRA = 32;
  public static final int SEGUN = 29;
  public static final int HACER = 30;
  public static final int INICIO = 2;
  public static final int ES_IGUAL = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "INGRESAR",
  "VARIABLE",
  "COMO",
  "CON_VALOR",
  "BOOLEAN",
  "NUMERO",
  "CARACTER",
  "CADENA",
  "LIT_NUMERO",
  "MAYOR",
  "MENOR",
  "MAYOR_O_IGUAL",
  "MENOR_O_IGUAL",
  "ES_IGUAL",
  "ES_DIFERENTE",
  "PUNTO_COMA",
  "LIT_CARACTER",
  "LIT_CADENA",
  "LIT_BOOLEAN",
  "ASIGNACION",
  "SI",
  "FIN_SI",
  "O_SI",
  "ENTONCES",
  "DE_LO_CONTRARIO",
  "SEGUN",
  "HACER",
  "INTERROGACION_ABRE",
  "INTERROGACION_CIERRA",
  "FIN_SEGUN",
  "IMPRIMIR",
  "IMPRIMIR_NL"
  };
}

